### ISSUE TITLE
archivo .aux

### ISSUE THREAD

**Issue by albpergar5** [ceciv21/TDGrupo3#4]
¿Qué es un archivo .aux? ¿Cómo se puede abrir?

**Comment by magjanvaz** [comment]
Al actualizar el pdf de la resolución de mi ejercicio se creó este archivo de forma automática, he decidido subirlo no sea que se produjera un error al eliminarlo, pero si alguien supiera cómo suprimirlo sin causar ningún problema agradezco la ayuda.

**Comment by albpergar5** [comment]
De acuerdo, intentaré investigar acerca de eso.

**Comment by magjanvaz** [comment]
Tras consultarlo con el profesor me ha indicado que los archivos con esta terminación pueden eliminarse sin problema, y he modificado el archivo .gitignore para que en caso de generarse más en el futuro no se suban al repositorio
