### ISSUE TITLE
archivo .out

### ISSUE THREAD

**Issue by albpergar5** [ceciv21/TDGrupo3#5]
Y este archivo al igual que el anterior, ¿cuál es su función?

**Comment by magjanvaz** [comment]
Este archivo al igual que el .aux los creó Rstudio a la vez que la salida pdf, tiene solo tres líneas de código cuya finalidad no termino de entender, precisamente por no saber cuál es su función he preferido subirlo sin modificar nada. Si consigo que se genere solo el pdf como la primera vez eliminaré los dos archivos.

**Comment by albpergar5** [comment]
Entendido, gracias.

**Comment by magjanvaz** [comment]
El archivo no tenía ninguna utilidad así que ha sido eliminado del repositorio.
