### ISSUE TITLE
Propuesta mejora ejercicio Concierto

### ISSUE THREAD

**Issue by magjanvaz** [ceciv21/TDGrupo3#6]
Tal vez podría añadirse para darle algo de complicación al ejercicio que alquilar el teatro le suponga un coste, mientras que al aire libre no tiene ese problema, por tanto a los beneficios del concierto en el teatro habría que restarle los costes que supuso.

**Comment by laura-gtzes** [comment]
Gracias por la propuesta, la he tomado en cuenta. Es muy interesante como al moverle un poco los valores, o en este caso agregarle costos, cambia el resultado.

**Comment by laura-gtzes** [comment]
Gracias por la propuesta, la he tomado en cuenta. Es muy interesante como al moverle un poco los valores, o en este caso agregarle costos, cambia el resultado.
